### PR TITLE
Update acts_as_tenant to avoid annoying Rails 5.1 deprecation

### PR DESCRIPTION
**Pull request by plicjo**

### CODE REVIEW

**Comment by plicjo** [comment]
You can view the difference between `0.4.0` and `0.4.1` here: https://github.com/ErwinM/acts_as_tenant/compare/2dd7d32d1f...master

The public API of the gem did not change. Features appear to have been added, not modified or removed.

**Comment by plicjo** [comment]
I misclicked the Review request. My bad! This is mergeable though. :D

**Comment by garyfoster** [comment]
this PR is assigned to me, but I don't see a task assigned, can point me to it?

**Comment by plicjo** [comment]
10-4. Here's the task: https://groundswell.groundswell.online/tasks/18798

**Comment by plicjo** [comment]
This upgrade is scheduled to occur in bulk with all the other gems on Thursday

**Pull request closed without merging**
